baseURL = 'https://sterna-conseil.com'
languageCode = 'fr-FR'
title = 'Sterna Conseil'
theme = 'minimal-consultant'

[params]
# Identité
company_name = 'Sterna Conseil'
description = 'Conseil stratégique et modélisation financière dynamique pour levées de fonds et opérations M&A'

# Contact
email = 'benoit@sterna-conseil.com'
linkedin = 'https://www.linkedin.com/in/benoitgrillaudinsead/'
morgen = 'https://morgen.so/benoit-sterna-conseil'

# Favicon
favicon = '/images/Favicon.ico'
logo = '/images/logo-sterna.png'

# Menu navigation
[[menu.main]]
name = 'Accueil'
url = '/'
weight = 5

[[menu.main]]
name = 'Avantages'
url = '#avantages'
weight = 10

[[menu.main]]
name = 'Services'
url = '#services'
weight = 15

[[menu.main]]
name = 'Équipe'
url = '#equipe'
weight = 20

[[menu.main]]
name = 'Contact'
url = '#contact'
weight = 25